[project]
name = "isaac-teleop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "catkin-pkg>=1.1.1",
    "cmake<3.31",
    "colcon-common-extensions>=0.3.0",
    "empy>=4.2.1",
    "lark-parser>=0.12.0",
    "pyelftools>=0.33",
    "west>=1.5.0",
]
